export enum TransactionType {
  SEND = 'send',
  RECEIVED = 'received',
  SWAPPED = 'swapped',
  APPROVED = 'approved',
  ADDED_LIQUIDITY = 'added-liquidity',
  REMOVE_LIQUIDITY = 'remove-liquidity',
  WITHDRAW_LIQUIDITY = 'withdraw-liquidity',
  CLAIMED_REWARDS = 'claimed-rewards',
  UNDEPOSIT_NFT = 'undeposit-nft',
  WITHDRAW_NFT = 'withdraw-nft',
  DEPOSIT_NFT = 'deposit-nft',
  STAKE = 'stake',
  UNSTAKE = 'unstake',
  WRAP = 'wrap',
  UNWRAP = 'unwrap',
  BUY_BOND = 'buy-bond',
  CLAIM_BOND = 'claim-bond',
  TRANSFER_BOND = 'transfer-bond',
  ZAP = 'zap',
  TRANSACTION = 'transaction',
}
